# -*- coding: utf-8 -*-
"""Generate the cube for the GENUINE 3sigma_g orbital of N2 (MO#4, -13.0 eV, non-degenerate).
The earlier n2_sg_homo.cube was MO#6 = a 1pi_u component (mislabelled); this fixes it."""
import numpy as np
from pyscf import gto, scf
from pyscf.tools import cubegen
mol = gto.M(atom="N 0 0 0; N 0 0 2.0", basis="cc-pvdz", verbose=0)
mf = scf.RHF(mol).run()
# render_sg.py needs n2.xyz; re-emit it here so this script + render_sg.py are a
# self-contained pair, without having to run the whole gen_cubes.py sweep first.
# Line 2 must not start with an element symbol -- PyMOL's XYZ reader would take the
# comment line for an atom record and silently collapse the molecule onto the origin.
_xyz = mol.atom_coords(unit="Angstrom")
with open("/w/n2.xyz", "w") as fh:
    fh.write(f"{mol.natm}\ngeometry in Angstrom, generated by figures/gen_sg_true.py\n")
    for i in range(mol.natm):
        fh.write("%s %.8f %.8f %.8f\n" % (mol.atom_pure_symbol(i), *_xyz[i]))
for idx, name in [(4, "sg_true")]:
    cubegen.orbital(mol, f"/w/n2_{name}.cube", mf.mo_coeff[:, idx], nx=90, ny=90, nz=90)
    print(f"n2 {name}: MO#{idx}  e={mf.mo_energy[idx]*27.211386:+.3f} eV", flush=True)
print("done")
