# -*- coding: utf-8 -*-
"""Generate Gaussian cube files for selected active-space MOs + save orbital energies,
and emit the .xyz geometries that render_orb.py / render_sg.py load into PyMOL.

The .xyz files are written from the Mole object rather than typed out by hand: the
ball-and-stick model and the isosurface have to come from the same geometry, and a
hand-maintained copy is exactly the kind of thing that silently drifts. Until
2026-09-11 no script in the repo wrote them at all, so the render step could not run
from a clean checkout."""
# GAUGE, declarado porque afecta a lo que se ve dibujado. Este script NO fija
# symmetry=True. Dentro de una capa pi degenerada la orientacion de cada orbital es
# arbitraria: rotarla deja la energia y la etiqueta de irrep intactas y cambia el dibujo.
# Lo que muestra la Fig. 2 es por tanto UN sorteo de esa familia, no "el" orbital, y con
# OMP_NUM_THREADS=1 ese sorteo es el determinista de 130.192 grados (gauge_study/
# determinismo.py). No se regenera con el gauge adaptado porque el render necesita PyMOL,
# que no es instalable en las imagenes depositadas; se declara en su lugar.
import numpy as np
from pyscf import gto, scf
from pyscf.tools import cubegen

def write_xyz(mol, path):
    """PyMOL reads .xyz in Angstrom; cube origins are in Bohr but self-describing.

    Line 2 is the XYZ comment line and must NOT look like an atom record: PyMOL's reader
    will happily parse "N 0 0 0; N 0 0 2.0" as an atom, shifting every subsequent line by
    one and silently dropping the last atom. That failure is invisible -- you get the right
    atom COUNT, all at the origin, so the molecule renders as a single sphere and cmd.orient
    then has nothing to orient. Keep this line free of leading element symbols."""
    xyz = mol.atom_coords(unit="Angstrom")
    with open(path, "w") as fh:
        fh.write(f"{mol.natm}\ngeometry in Angstrom, generated by figures/gen_cubes.py\n")
        for i in range(mol.natm):
            x, y, z = xyz[i]
            fh.write(f"{mol.atom_pure_symbol(i)} {x:.8f} {y:.8f} {z:.8f}\n")
    print(f"wrote {path}", flush=True)

def do(tag, atom, picks):
    mol = gto.M(atom=atom, basis="cc-pvdz", verbose=0)
    mf = scf.RHF(mol).run()
    nocc = mol.nelectron // 2
    np.save(f"/w/{tag}_moe.npy", mf.mo_energy)
    np.save(f"/w/{tag}_nocc.npy", np.array([nocc]))
    write_xyz(mol, f"/w/{tag}.xyz")
    for idx, name in picks:
        cubegen.orbital(mol, f"/w/{tag}_{name}.cube", mf.mo_coeff[:, idx],
                        nx=90, ny=90, nz=90)
        print(f"{tag} {name}: MO#{idx}  e={mf.mo_energy[idx]:+.3f} Ha", flush=True)
    return mf.mo_energy, nocc

# N2 (nocc=7): MO#4 = 3sigma_g (A1g, -13.0 eV), MO#5/6 = 1pi_u HOMO pair (E1u, -10.9 eV),
# MO#7/8 = 1pi_g* LUMO pair (E1g, -2.3 eV), MO#9 = 3sigma_u* (A1u).
# "sg_homo" below is MO#6 and is therefore a 1pi_u component, NOT 3sigma_g -- the name is
# kept only so the legacy o_n2_sg.png keeps building. Figure 2 uses gen_sg_true.py (MO#4).
do("n2", "N 0 0 0; N 0 0 2.0",
   [(5, "piu_homo1"), (6, "sg_homo"), (7, "pig_lumo"), (9, "su_lumo3")])
# H2O (nocc=5): HOMO=4 (1b1 lone pair), LUMO=5 (4a1*)
do("h2o", "O 0 0 0; H 0 0.98 0.76; H 0 -0.98 0.76",
   [(3, "a1_homo1"), (4, "b1_homo"), (5, "a1_lumo")])
print("cubes done")
